name: material

features:
- header.autohide
- navigation.footer

palette:
- scheme: default
  toggle:
    icon: material/weather-night
    name: Switch to dark mode

- scheme: slate
  toggle:
    icon: material/weather-sunny
    name: Switch to light mode
